export const Routes = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  USERS: "/users",
  USERS_DETAIL: (id: string) => `/user-detail/${id}`,
  PRODUCTS: "/products",
  PRODUCTS_DETAIL: (id: number) => `/product-detail/${id}`,
  ADD_PRODUCT: "/add-product",
  EDIT_PRODUCT: (id: number) => `/edit-product/${id}`,
  GOALS: "/goals",
  ORDERS: "/orders",
  ORDER_HISTORY: "/order-history",
  STOCK_HISTORY: "/stock-history",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  FAQS: "/faqs",
};
